version: "3"

services:
  codelab_app:
    container_name: codelab_app
    build:
      context: .docker
      dockerfile: Dockerfile
      args:
        - NODE_ENV=developement
    entrypoint: .docker/entrypoint.sh
    volumes:
      - .:/home/node/app
