version: "3"

services:
  hello-codelab:
    container_name: hello-codelab
    # image: hello:2.0
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    volumes:
      - ./:/app
