version: '3'

services:
  codelab_pg:
    image: postgres:16.2
    container_name: codelab_pg
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - codelab_pg:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  codelab_pg: